 ##############################################################################
 # Makefile "3D-ICE/makefile.def"                                             #
 #                                                                            #
 # This file is part of 3D-ICE 1.0 (beta).                                    #
 #                                                                            #
 # 3D-ICE is free software: you can  redistribute it and/or  modify it  under #
 # the terms of the  GNU General  Public  License as  published by  the  Free #
 # Software  Foundation, either  version  3  of  the License,  or  any  later #
 # version.                                                                   #
 #                                                                            #
 # 3D-ICE is  distributed  in the hope  that it will  be useful, but  WITHOUT #
 # ANY  WARRANTY; without  even the  implied warranty  of MERCHANTABILITY  or #
 # FITNESS  FOR A PARTICULAR  PURPOSE. See the GNU General Public License for #
 # more details.                                                              #
 #                                                                            #
 # You should have  received a copy of  the GNU General  Public License along #
 # with 3D-ICe. If not, see <http://www.gnu.org/licenses/>.                   #
 #                                                                            #
 #                             Copyright (C) 2010                             #
 #   Embedded Systems Laboratory - Ecole Polytechnique Federale de Lausanne   #
 #                            All Rights Reserved.                            #
 #                                                                            #
 # Authors: Arvind Sridhar                                                    #
 #          Alessandro Vincenzi                                               #
 #          Martino Ruggiero                                                  #
 #          Thomas Brunschwiler                                               #
 #          David Atienza                                                     #
 #                                                                            #
 # EPFL-STI-IEL-ESL                                                           #
 # Bstiment ELG, ELG 130                                                      #
 # Station 11                                           3d-ice@listes.epfl.ch #
 # 1015 Lausanne, Switzerland                  http://esl.epfl.ch/3d-ice.html #
 ##############################################################################

 #
 # Thermal Library variables
 ##############################################################################

3DICE_LIBNAME   = 3D-ICE
3DICE_VERSION   = 1.0-beta

3DICE_INCLUDE   = $(3DICE_MAIN)/include
3DICE_FLEX      = $(3DICE_MAIN)/flex
3DICE_BISON     = $(3DICE_MAIN)/bison
3DICE_SOURCES   = $(3DICE_MAIN)/sources
3DICE_LIB       = $(3DICE_MAIN)/lib
3DICE_EXAMPLES  = $(3DICE_MAIN)/examples

3DICE_FLEX_L    = $(3DICE_FLEX)/floorplan_scanner.l         \
                  $(3DICE_FLEX)/stack_description_scanner.l
3DICE_FLEX_C    = $(3DICE_FLEX_L:.l=.c)
3DICE_FLEX_H    = $(3DICE_FLEX_L:.l=.h)
3DICE_FLEX_O    = $(3DICE_FLEX_L:.l=.o)
3DICE_FLEX_D    = $(3DICE_FLEX_L:.l=.d)

3DICE_BISON_Y   = $(3DICE_BISON)/floorplan_parser.y         \
                  $(3DICE_BISON)/stack_description_parser.y
3DICE_BISON_C   = $(3DICE_BISON_Y:.y=.c)
3DICE_BISON_H   = $(3DICE_BISON_Y:.y=.h)
3DICE_BISON_O   = $(3DICE_BISON_Y:.y=.o)
3DICE_BISON_D   = $(3DICE_BISON_Y:.y=.d)

3DICE_INCLUDE_H = $(3DICE_INCLUDE)/channel.h                \
                  $(3DICE_INCLUDE)/conductances.h           \
                  $(3DICE_INCLUDE)/die.h                    \
                  $(3DICE_INCLUDE)/dimensions.h             \
                  $(3DICE_INCLUDE)/environment_heat_sink.h  \
                  $(3DICE_INCLUDE)/floorplan_element.h      \
                  $(3DICE_INCLUDE)/floorplan.h              \
                  $(3DICE_INCLUDE)/layer.h                  \
                  $(3DICE_INCLUDE)/material.h               \
                  $(3DICE_INCLUDE)/powers_queue.h           \
                  $(3DICE_INCLUDE)/stack_description.h      \
                  $(3DICE_INCLUDE)/stack_element.h          \
                  $(3DICE_INCLUDE)/system_matrix.h          \
                  $(3DICE_INCLUDE)/system_vector.h          \
                  $(3DICE_INCLUDE)/thermal_data.h           \
                  $(3DICE_INCLUDE)/types.h

3DICE_SOURCES_C = $(3DICE_SOURCES)/channel.c                \
                  $(3DICE_SOURCES)/conductances.c           \
                  $(3DICE_SOURCES)/die.c                    \
                  $(3DICE_SOURCES)/dimensions.c             \
                  $(3DICE_SOURCES)/environment_heat_sink.c  \
                  $(3DICE_SOURCES)/floorplan_element.c      \
                  $(3DICE_SOURCES)/floorplan.c              \
                  $(3DICE_SOURCES)/layer.c                  \
                  $(3DICE_SOURCES)/material.c               \
                  $(3DICE_SOURCES)/powers_queue.c           \
                  $(3DICE_SOURCES)/stack_description.c      \
                  $(3DICE_SOURCES)/stack_element.c          \
                  $(3DICE_SOURCES)/system_matrix.c          \
                  $(3DICE_SOURCES)/thermal_data.c

3DICE_SOURCES_O = $(3DICE_SOURCES_C:.c=.o)
3DICE_SOURCES_D = $(3DICE_SOURCES_C:.c=.d)

3DICE_LIB_A     = $(3DICE_LIB)/lib$(3DICE_LIBNAME)-$(3DICE_VERSION).a

3DICE_LIB_O     = $(3DICE_FLEX_O) $(3DICE_BISON_O) $(3DICE_SOURCES_O)

3DICE_ALL_FILES = $(3DICE_BISON_Y)            \
                  $(3DICE_BISON)/Makefile     \
                  $(3DICE_FLEX_L)             \
                  $(3DICE_FLEX)/Makefile      \
                  $(3DICE_INCLUDE_H)          \
                  $(3DICE_LIB)                \
                  $(3DICE_LIB)/Makefile       \
                  $(3DICE_SOURCES_C)          \
                  $(3DICE_SOURCES_C)/Makefile \
                  makefile.def                \
                  Makefile                    \
                  COPYING                     \
                  README

 #
 # SuperLU variables
 ##############################################################################

SLU_MAIN    = $(HOME)/SuperLU_4.0
SLU_INCLUDE = $(SLU_MAIN)/SRC
SLU_LIB     = $(SLU_MAIN)/lib
SLU_LIBS    = -L$(SLU_LIB) -lsuperlu_4.0 -lblas
#SLU_LIBS    = -L$(SLU_LIB) -lsuperlu_4.0 -L/usr/lib64 -lblas

 #
 # Commands and flags
 ##############################################################################

AR        = ar
ARFLAGS   = rsv

CC        = gcc
CFLAGS    = -MD -g
CINCLUDES = -I$(3DICE_INCLUDE)

YACC      = bison
YFLAGS    = -d

LEX       = flex
LFLAGS    =

RM        = rm
RMFLAGS   = -vf

 #
 # Pattern rules
 ##############################################################################

%.c: %.y
	$(YACC) $(YFLAGS) $(notdir $<)

%.c: %.l
	$(LEX) $(LFLAGS) $(notdir $<)

%.o : %.c
	$(CC) $(CFLAGS) $(CINCLUDES) -c $< -o $@
	@cp $*.d $*.dd
	@sed -e 's/#.*//'       \
             -e 's/^[^:]*: *//' \
             -e 's/ *\\$$//'    \
	     -e '/^$$/ d'       \
             -e 's/$$/ :/' < $*.dd >> $*.d
	@rm -f $*.dd
