#******************************************************************************
#*                                                                            *
#* makefile.def                                                               *
#*                                                                            *
#* EPFL-STI-IEL-ESL                                                           *
#* Bâtiment ELG, ELG 130                                                      *
#* Station 11                                                                 *
#* 1015 Lausanne, Switzerland                    alessandro.vincenzi@epfl.ch  *
#******************************************************************************

TL_LIB_DIR     = $(TL_MAIN_DIR)/Lib
TL_INCLUDE_DIR = $(TL_MAIN_DIR)/Include

TL_LIB_A = $(TL_LIB_DIR)/libThermalLibrary.a
