###############################################################################
# Makefile "hotspot2threedice/makefile.def"                                   #
#                                                                             #
# This file is part of 3D-ICe (http://esl.epfl.ch/3D-ICe), revision 0.1       #
#                                                                             #
# 3D-ICe is free software: you can redistribute it and/or modify it under     #
# the terms of the GNU General Public License as published by the Free        #
# Software Foundation, either version 3 of the License, or any later          #
# version.                                                                    #
#                                                                             #
# 3D-ICe is distributed in the hope that it will be useful, but WITHOUT       #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or       #
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for    #
# more details.                                                               #
#                                                                             #
# You should have received a copy of the GNU General Public License along     #
# with 3D-ICe.  If not, see <http://www.gnu.org/licenses/>.                   #
#                                                                             #
# Copyright (C) 2010,                                                         #
# Embedded Systems Laboratory - Ecole Polytechnique Federale de Lausanne.     #
# All Rights Reserved.                                                        #
#                                                                             #
# Authors: Alessandro Vincenzi, Arvind Sridhar.                               #
#                                                                             #
# EPFL-STI-IEL-ESL                                                            #
# Bâtiment ELG, ELG 130                                                       #
# Station 11                                                                  #
# 1015 Lausanne, Switzerland                          threed-ice@esl.epfl.ch  #
###############################################################################

#
# HotSpot2threedice variables
###############################################################################

HS2TDICE_INCLUDE = $(HS2TDICE_MAIN)/include
HS2TDICE_SOURCES = $(HS2TDICE_MAIN)/sources
HS2TDICE_BISON   = $(HS2TDICE_MAIN)/bison
HS2TDICE_FLEX    = $(HS2TDICE_MAIN)/flex
HS2TDICE_BIN     = $(HS2TDICE_MAIN)/bin

HS2TDICE_FLEX_OBJECTS    = $(HS2TDICE_FLEX)/hotspot_flp_scanner.o    \
                           $(HS2TDICE_FLEX)/hotspot_ptrace_scanner.o

HS2TDICE_BISON_OBJECTS   = $(HS2TDICE_BISON)/hotspot_flp_parser.o    \
                           $(HS2TDICE_BISON)/hotspot_ptrace_parser.o

HS2TDICE_SOURCES_OBJECTS = $(HS2TDICE_SOURCES)/hotspot2threedice.o

HS2TDICE_EXE_OBJECTS     = $(HS2TDICE_FLEX_OBJECTS)    \
                           $(HS2TDICE_BISON_OBJECTS)   \
                           $(HS2TDICE_SOURCES_OBJECTS)

HS2TDICE_EXE             = $(HS2TDICE_BIN)/hotspot2threedice

#
# 3D-Ice Library variables
###############################################################################

TDICE_MAIN        = $(HS2TDICE_MAIN)/..
TDICE_INCLUDE     = $(TDICE_MAIN)/include
TDICE_LIB         = $(TDICE_MAIN)/lib
TDICE_LIB_ARCHIVE = $(TDICE_LIB)/libthreedice.a

#
# Commands and flags
###############################################################################

CC        = gcc
CFLAGS    = -MD -g
CINCLUDES =
CLIBS     =

YACC      = bison
YFLAGS    = -d

LEX       = flex
LFLAGS    =

RM        = rm
RMFLAGS   = -vf

#
# Pattern rules
###############################################################################

%.c: %.y
	$(YACC) $(YFLAGS) $(notdir $<)

%.c: %.l
	$(LEX) $(LFLAGS) $(notdir $<)

%.o : %.c
	$(CC) $(CFLAGS) $(CINCLUDES) -c $< -o $@
	@cp $*.d $*.dd
	@sed -e 's/#.*//'       \
             -e 's/^[^:]*: *//' \
             -e 's/ *\\$$//'    \
	     -e '/^$$/ d'       \
             -e 's/$$/ :/' < $*.dd >> $*.d
	@rm -f $*.dd

